import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { Button } from "@/ui/Button";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="h-[80px] flex justify-between items-center px-10 border-b border-b-borderDark">
        <div className="text-4xl font-medium">sportclub</div>
        <AuthShowcase />
      </header>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="flex flex-col items-center gap-2">
          {/* <AuthShowcase /> */}
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  console.log(sessionData);
  
  return (
    <div className="flex items-center justify-center gap-5">
      <p className="text-center text-p text-white">
        {sessionData && <span>{sessionData.user?.email}</span>}
      </p>
      <Button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Вийти" : "Увійти"}
      </Button>
    </div>
  );
};
